services:
  # --- MySQL ---
  mysql-bdd:
    image: mysql:8
    container_name: mysql-bdd
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./bdd-mysql2:/docker-entrypoint-initdb.d

  # --- phpMyAdmin ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: mysql-bdd
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql-bdd

  # --- Fastify API ---
  api:
    build: ./api
    container_name: fastify-api
    restart: always
    env_file:
      - .env
    environment:
      MYSQLHOST: ${MYSQLHOST}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      MYSQLDATABASE: ${MYSQLDATABASE}
      JWT_SECRET: ${JWT_SECRET}
      VITE_API_URL: ${VITE_API_URL}
      MJ_APIKEY_PUBLIC: ${MJ_APIKEY_PUBLIC}
      MJ_APIKEY_PRIVATE: ${MJ_APIKEY_PRIVATE}
      COOKIE_SECRET: ${COOKIE_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - mysql-bdd

  # --- Quasar Frontend (Dev Mode) ---
  front-quasar:
    build: ./front-quasar
    container_name: front-quasar
    command: ["sh", "-c", "npm install && quasar dev --hostname 0.0.0.0"]

    environment:
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_INTERVAL: 750
      VITE_API_URL: ${VITE_API_URL}

    volumes:
      - ./front-quasar:/app
      - /app/node_modules

    ports:
      - "8080:8080"

volumes:
  mysql_data:
